# Generated by Django 2.1.1 on 2018-10-26 16:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('plex_id', models.CharField(blank=True, max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigWebServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_trakt_username', models.CharField(blank=True, max_length=254, verbose_name='Trakt API Username')),
                ('api_key_trakt_client_id', models.CharField(blank=True, max_length=254, verbose_name='Trakt API Client ID')),
                ('api_key_trakt_client_secret', models.CharField(blank=True, max_length=254, verbose_name='Trakt API Client Secret')),
                ('api_key_tvdb', models.CharField(blank=True, max_length=254, verbose_name='TVDB API Key')),
            ],
        ),
        migrations.CreateModel(
            name='TvShowModel',
            fields=[
                ('tvdb_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='TVDB Id')),
                ('sonarr_id', models.IntegerField(unique=True, verbose_name='Sonarr Id')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('slug', models.CharField(max_length=254, verbose_name='Title Slug')),
                ('overview', models.TextField(blank=True, verbose_name='Overview')),
                ('image_url_banner', models.URLField(blank=True, max_length=254, verbose_name='Banner Image URL')),
                ('image_url_poster', models.URLField(blank=True, max_length=254, verbose_name='Poster Image URL')),
                ('image_url_fanart', models.URLField(blank=True, max_length=254, verbose_name='Fan Art Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('manager', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.UserProfileModel'),
        ),
    ]
