# Generated by Django 2.1.1 on 2018-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20181009_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWebServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_trakt_client_id', models.CharField(blank=True, max_length=254, verbose_name='Trakt API Client ID')),
                ('api_key_trakt_client_secret', models.CharField(blank=True, max_length=254, verbose_name='Trakt API Client Secret')),
                ('api_key_tvdb', models.CharField(blank=True, max_length=254, verbose_name='TVDB API Key')),
            ],
        ),
    ]
