# Generated by Django 2.1.1 on 2018-10-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_configwebservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='configwebservices',
            name='api_key_trakt_username',
            field=models.CharField(blank=True, max_length=254, verbose_name='Trakt API Username'),
        ),
    ]
