# Generated by Django 2.1.1 on 2018-10-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_configwebservices_api_key_trakt_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('tvdb_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='TVDB Id')),
                ('sonarr_id', models.IntegerField(unique=True, verbose_name='Sonarr Id')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('slug', models.CharField(max_length=254, verbose_name='Title Slug')),
                ('overview', models.TextField(blank=True, verbose_name='Overview')),
                ('image_url_banner', models.URLField(blank=True, max_length=254, verbose_name='Banner Image URL')),
                ('image_url_poster', models.URLField(blank=True, max_length=254, verbose_name='Poster Image URL')),
                ('image_url_fanart', models.URLField(blank=True, max_length=254, verbose_name='Fan Art Image URL')),
            ],
        ),
    ]
