# Generated by Django 2.1.1 on 2018-10-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_tvshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigWebServices',
            new_name='ConfigWebService',
        ),
    ]
