# Generated by Django 2.1.1 on 2018-10-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20181025_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
